/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jlist;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HaiApple.Com
 */
public class JList extends javax.swing.JFrame {

    /**
     * Creates new form JList
     */
    public JList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTong = new javax.swing.JPanel();
        pnTren = new javax.swing.JPanel();
        lblThaoTac = new javax.swing.JLabel();
        pnDuoi = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        pnTrai = new javax.swing.JPanel();
        btnToSoChan = new javax.swing.JButton();
        btnSoLe = new javax.swing.JButton();
        btnSoNguyenTo = new javax.swing.JButton();
        btnBoToDen = new javax.swing.JButton();
        btnXoaGTToDen = new javax.swing.JButton();
        btnTongGiaTri = new javax.swing.JButton();
        pnGiua = new javax.swing.JPanel();
        btnNhap = new javax.swing.JButton();
        txtNhap = new javax.swing.JTextField();
        ckbChoNhapSoAm = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        LstThongTin = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTong.setLayout(new java.awt.BorderLayout());

        lblThaoTac.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblThaoTac.setForeground(new java.awt.Color(0, 0, 255));
        lblThaoTac.setText("Thao tác trên JList - CheckBox");
        pnTren.add(lblThaoTac);

        pnTong.add(pnTren, java.awt.BorderLayout.PAGE_START);

        pnDuoi.setBackground(new java.awt.Color(255, 153, 153));
        pnDuoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setText("Đóng chương trình");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnDuoi.add(btnThoat);

        pnTong.add(pnDuoi, java.awt.BorderLayout.PAGE_END);

        pnTrai.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Chọn tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        pnTrai.setLayout(new javax.swing.BoxLayout(pnTrai, javax.swing.BoxLayout.Y_AXIS));

        btnToSoChan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnToSoChan.setText("Tô đen số chẵn");
        btnToSoChan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnToSoChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToSoChanActionPerformed(evt);
            }
        });
        pnTrai.add(btnToSoChan);

        btnSoLe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSoLe.setText("Tô đen số lẻ");
        btnSoLe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnTrai.add(btnSoLe);

        btnSoNguyenTo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSoNguyenTo.setText("Tô đen số nguyên tố");
        btnSoNguyenTo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnTrai.add(btnSoNguyenTo);

        btnBoToDen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBoToDen.setText("Bỏ tô đen");
        btnBoToDen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnTrai.add(btnBoToDen);

        btnXoaGTToDen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnXoaGTToDen.setText("Xóa các giá trị đang tô đen");
        btnXoaGTToDen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnTrai.add(btnXoaGTToDen);

        btnTongGiaTri.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTongGiaTri.setText("Tổng giá trị trong JList");
        btnTongGiaTri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnTrai.add(btnTongGiaTri);

        pnTong.add(pnTrai, java.awt.BorderLayout.LINE_START);

        pnGiua.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Nhập thông tin:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        btnNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhap.setText("Nhập");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        txtNhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        ckbChoNhapSoAm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ckbChoNhapSoAm.setText("Cho nhập số âm");

        jScrollPane2.setViewportView(LstThongTin);

        javax.swing.GroupLayout pnGiuaLayout = new javax.swing.GroupLayout(pnGiua);
        pnGiua.setLayout(pnGiuaLayout);
        pnGiuaLayout.setHorizontalGroup(
            pnGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(pnGiuaLayout.createSequentialGroup()
                        .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckbChoNhapSoAm)))
                .addContainerGap())
        );
        pnGiuaLayout.setVerticalGroup(
            pnGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbChoNhapSoAm)
                    .addComponent(btnNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTong.add(pnGiua, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Muốn thoát à?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (k == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed
    private DefaultListModel<Integer> model;
    DefaultListModel dlm = new DefaultListModel();
    private void btnToSoChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToSoChanActionPerformed
        model = new DefaultListModel<Integer>();
        ArrayList<Integer> m = new ArrayList<Integer>();
        int[] mSelected;
        for (int i=0; i<model.getSize(); i++)
        {
            if((model.getElementAt(i) % 2) == 0)
            m.add(i);
        }
        mSelected = convertIntegers(m);
        LstThongTin.setSelectedIndices(mSelected);
    }//GEN-LAST:event_btnToSoChanActionPerformed
    
    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        int a;
        boolean kk = true;
        String sa = txtNhap.getText();
        if (ckbChoNhapSoAm.isSelected()) {
            kk = true;
        } else {
            kk = false;
        }

        try {
            a = Integer.parseInt(sa);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(null, "Nhập sai rồi");
            txtNhap.requestFocus();
            return;
        }
        if (a < 0) {
            if (kk == false) {

                JOptionPane.showMessageDialog(null, "Không cho nhập số âm!!Nhập lại đi!!");
                txtNhap.requestFocus();
                return;
            } else {
                LstThongTin.setModel(dlm);
                dlm.addElement(sa);
                txtNhap.setText("");
            }
        } else {
            LstThongTin.setModel(dlm);
            dlm.addElement(sa);
            txtNhap.setText("");
        }
    }//GEN-LAST:event_btnNhapActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LstThongTin;
    private javax.swing.JButton btnBoToDen;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSoLe;
    private javax.swing.JButton btnSoNguyenTo;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnToSoChan;
    private javax.swing.JButton btnTongGiaTri;
    private javax.swing.JButton btnXoaGTToDen;
    private javax.swing.JCheckBox ckbChoNhapSoAm;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblThaoTac;
    private javax.swing.JPanel pnDuoi;
    private javax.swing.JPanel pnGiua;
    private javax.swing.JPanel pnTong;
    private javax.swing.JPanel pnTrai;
    private javax.swing.JPanel pnTren;
    private javax.swing.JTextField txtNhap;
    // End of variables declaration//GEN-END:variables

    private int[] convertIntegers(ArrayList<Integer> m) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
